In [1]:
#ufunc
import numpy as np

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [9]:
#Simple Arithmetic

import numpy as np
arr1 = np.array([10,12,14,16,18])
arr2 = np.array([5,6,7,8,9])

#Addition
newarr = np.add(arr1,arr2)
print(newarr)

#Subtraction
newarr1 = np.subtract(arr1,arr2)
print(newarr1)

#Multiplication
newarr2 = np.multiply(arr1,arr2)
print(newarr2)

#division
newarr3 = np.divide(arr1,arr2)
print(newarr3)

#power
newarr4 = np.power(arr1,arr2)
print(newarr4)

#remainder
newarr5 = np.mod(arr1,arr2)
print(newarr5)

[15 18 21 24 27]
[5 6 7 8 9]
[ 50  72  98 128 162]
[2. 2. 2. 2. 2.]
[   100000   2985984 105413504         0 790794752]
[0 0 0 0 0]


In [15]:
#Rounding Decimals

# Rounding Decimals
# There are primarily five ways of rounding off decimals in NumPy:

# truncation
# fix
# rounding
# floor
# ceil

import numpy as np

arr = np.trunc([-3.1666, 3.6667])
print(arr)

arr = np.fix([-3.1666, 3.6667])
print(arr)

arr = np.around([-3.1666, 3.6667])
print(arr)

arr = np.floor([-3.1666, 3.6667])
print(arr)

arr = np.ceil([-3.1666, 3.6667])
print(arr)

[-3.  3.]
[-3.  3.]
[-3.  4.]
[-4.  3.]
[-3.  4.]


In [21]:
#NumPy Logs

# Log at Base 2
# Use the log2() function to perform log at the base 2.

import numpy as np

arr = np.arange(1,10)
print(arr)

print(np.log(arr))

print(np.log2(arr))

print(np.log10(arr))


[1 2 3 4 5 6 7 8 9]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [29]:
#Summations
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

#Summation Over an Axis
newarr = np.sum([arr1, arr2],axis=1)
print(newarr)

#product

newarr = np.prod([arr1, arr2])

print(newarr)

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

#Difference
newarr = np.diff([arr1, arr2], axis=1)

print(newarr)

12
[6 6]
36
[6 6]
[[1 1]
 [1 1]]


In [33]:
#Finding LCM (Lowest Common Multiple) 

import numpy as np

num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

arr = np.array([2,4,6,8,10])
print(np.lcm.reduce(arr))

12
120


In [34]:
#Finding GCD (Greatest Common Denominator)

import numpy as np

num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

print(np.gcd(3,4))

arr = np.array([2,4,6,8,10])
print(np.gcd.reduce(arr))

3
1
2


In [35]:
#NumPy Trigonometric Functions

import numpy as np

x = np.sin(np.pi/2)

print(x)

x = np.cos(np.pi/2)

print(x)

x = np.tan(np.pi/2)

print(x)

1.0
6.123233995736766e-17
1.633123935319537e+16


In [37]:
#Convert Degrees Into Radians

arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

#Convert Degrees Radians  Into Degrees

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]
[ 90. 180. 270. 360.]


In [38]:
# Finding Angles
# Finding angles from values of sine, cos, tan. E.g. sin, cos and tan inverse (arcsin, arccos, arctan).

# NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values given.


import numpy as np

x = np.arcsin(1.0)

print(x)

x = np.arccos(1.0)

print(x)

x = np.arctan(1.0)

print(x)

1.5707963267948966
0.0
0.7853981633974483


In [40]:
# NumPy Hyperbolic Functions

# NumPy provides the ufuncs sinh(), cosh() and tanh() that take values in radians and produce the corresponding sinh, cosh and tanh values..

import numpy as np

x = np.sinh(np.pi/2)

print(x)

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.cosh(arr)

print(x)

2.3012989023072947
[2.50917848 1.60028686 1.32460909 1.20397209]


In [44]:
#NumPy Set Operations

# What is a Set
# A set in mathematics is a collection of unique elements.

# Sets are used for operations involving frequent intersection, union and difference operations.

import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

#Finding Union

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

#Finding Intersection

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

#Finding Difference

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)


[1 2 3 4 5 6 7]
[1 2 3 4 5 6]
[3 4]
